# Generated by Django 5.1 on 2024-10-07 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("b_name", models.CharField(max_length=50)),
                ("b_ifsc", models.IntegerField()),
                ("b_addres", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "bank_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="multilevelinheritance.bank",
                    ),
                ),
                ("l_name", models.CharField(max_length=50)),
                ("rateofintrest", models.FloatField()),
                ("duration", models.CharField(max_length=50)),
            ],
            bases=("multilevelinheritance.bank",),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "loan_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="multilevelinheritance.loan",
                    ),
                ),
                ("u_name", models.CharField(max_length=60)),
                ("u_mobile", models.BigIntegerField()),
                ("u_email", models.EmailField(max_length=254)),
            ],
            bases=("multilevelinheritance.loan",),
        ),
    ]
