# Generated by Django 5.1 on 2024-10-07 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                ("b_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("b_name", models.CharField(max_length=50)),
                ("b_address", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                ("l_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("l_name", models.CharField(max_length=30)),
                ("l_intrest", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "loan_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="multipleinh.loan",
                    ),
                ),
                (
                    "bank_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="multipleinh.bank",
                    ),
                ),
                ("c_name", models.CharField(max_length=60)),
                ("c_email", models.EmailField(max_length=254)),
            ],
            bases=("multipleinh.bank", "multipleinh.loan"),
        ),
    ]
